#!/bin/bash

echo "🧹 CoderX Cookie Cleaner"
echo "======================="
echo ""
echo "This script will help you clear the browser cookies that might be"
echo "causing the 'Payment Required' error by remembering the wrong model."
echo ""
echo "📋 Instructions:"
echo "1. Open your browser"
echo "2. Go to: http://localhost:5173"
echo "3. Open Developer Tools (F12)"
echo "4. Go to Application/Storage tab"
echo "5. Find 'Cookies' section"
echo "6. Delete these cookies:"
echo "   - selectedModel"
echo "   - selectedProvider"
echo "   - apiKeys"
echo "7. Refresh the page (Ctrl+Shift+R or Cmd+Shift+R)"
echo ""
echo "🔄 Alternative - Clear All Cookies:"
echo "1. Press Ctrl+Shift+Delete (or Cmd+Shift+Delete on Mac)"
echo "2. Select 'Cookies and other site data'"
echo "3. Click 'Clear data'"
echo "4. Refresh the page"
echo ""
echo "✅ After clearing cookies:"
echo "- The app will automatically select a FREE model"
echo "- You should see 'openai/gpt-oss-20b:free' selected"
echo "- The pricing should show 'in:$0.00 out:$0.00'"
echo ""
echo "🎯 If you still get 'Payment Required' error:"
echo "1. Make sure you're using the model with ':free' suffix"
echo "2. Check that the pricing shows '$0.00' for both input and output"
echo "3. Enable 'Show Free Models Only' filter in the model selector"
echo ""
echo "✅ Cookie cleaning instructions complete!"
