#!/bin/bash

echo "🔧 CoderX Complete Reset Script"
echo "==============================="
echo ""
echo "You're still getting 'Payment Required' because the browser"
echo "is stubbornly holding onto the paid model selection."
echo ""
echo "Let's do a COMPLETE reset:"
echo ""
echo "1. 🌐 Open your browser"
echo "2. 📍 Go to: http://localhost:5173"
echo "3. 🗑️  COMPLETE BROWSER RESET:"
echo "   - Press Ctrl+Shift+Delete (or Cmd+Shift+Delete on Mac)"
echo "   - Select 'All time'"
echo "   - Check ALL boxes:"
echo "     ✓ Browsing history"
echo "     ✓ Cookies and other site data"
echo "     ✓ Cached images and files"
echo "     ✓ Download history"
echo "     ✓ Autofill form data"
echo "     ✓ Site settings"
echo "   - Click 'Clear data'"
echo ""
echo "4. 🔄 CLOSE AND REOPEN BROWSER:"
echo "   - Close the browser completely"
echo "   - Reopen the browser"
echo "   - Go to: http://localhost:5173"
echo ""
echo "5. ✅ VERIFY FREE MODEL:"
echo "   - Look for: 'openai/gpt-oss-20b:free' (with ':free')"
echo "   - Pricing: 'in:$0.00 out:$0.00'"
echo "   - NOT: 'openai/gpt-oss-20b' (without ':free')"
echo "   - NOT: 'in:$0.03 out:$0.14'"
echo ""
echo "6. 🎯 IF STILL WRONG MODEL:"
echo "   - Click the model dropdown"
echo "   - Find 'openai/gpt-oss-20b:free'"
echo "   - Select it manually"
echo ""
echo "7. 💬 TEST: Send a message - should work!"
echo ""
echo "🎉 This COMPLETE reset will force the free model selection!"
