#!/bin/bash

echo "🔧 CoderX Browser Reset Script"
echo "=============================="
echo ""
echo "The 400 Bad Request error is caused by browser cache/cookies."
echo "Follow these steps to fix it:"
echo ""
echo "1. 🌐 Open your browser"
echo "2. 📍 Go to: http://localhost:5173"
echo "3. 🗑️  Clear everything:"
echo "   - Press Ctrl+Shift+Delete (or Cmd+Shift+Delete on Mac)"
echo "   - Select 'All time'"
echo "   - Check 'Cookies and other site data'"
echo "   - Check 'Cached images and files'"
echo "   - Click 'Clear data'"
echo ""
echo "4. 🔄 Hard refresh:"
echo "   - Press Ctrl+Shift+R (or Cmd+Shift+R on Mac)"
echo ""
echo "5. ✅ Verify:"
echo "   - Model should show: openai/gpt-oss-20b:free"
echo "   - Provider should show: OpenRouter"
echo "   - Pricing should show: in:$0.00 out:$0.00"
echo ""
echo "6. 💬 Test: Send a message - it should work!"
echo ""
echo "🎯 If it still doesn't work:"
echo "   - Close the browser completely"
echo "   - Reopen the browser"
echo "   - Go to http://localhost:5173"
echo ""
echo "✅ This will fix the 400 Bad Request error!"
