blank_issues_enabled: false
contact_links:
  - name: CoderX related issues
    url: https://github.com/Suryanshu-Nabheet/CoderX/issues/new/choose
    about: Report issues related to CoderX
  - name: Chat
    url: https://github.com/Suryanshu-Nabheet/CoderX/discussions
    about: Ask questions and discuss with other CoderX users.
